[package]
name = "unwrap_or_else"
description = "Deny fallback closures that substitute values for missing data."
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
dylint_linting = { git = "https://github.com/trailofbits/dylint.git", rev = "9adfa398661273ca7dc99df9bf2c26ae6f61b1c5" }

[package.metadata.rust-analyzer]
rustc_private = true

[lints]
workspace = true
